language: rust

rust:
  - nightly

branches:
  only:
    - master

notifications:
  email:
    - sammy.james@protonmail.com

before_script:
  - sudo apt-get update -qq
  - sudo apt-get install libgtk-3-dev libglib2.0-dev -y

script:
  - cargo build --verbose
