language: rust

rust:
  - nightly

branches:
  only:
    - master

notifications:
  email:
    - sammy.morgan.james+github@gmail.com

before_script:
  - sudo apt-get update -qq
  - sudo apt-get install libgtk-3-dev -y

script:
  - cargo build --verbose