[package]
name = "tweetsie"
version = "0.1.0"
authors = ["Sammy James"]

[dependencies]
hyper = "0.10"
futures = "0.1.9"
secstr = "*"
lazy_static = "*"

[dependencies.gtk]
git = "https://github.com/gtk-rs/gtk.git"
features = ["v3_16"]