[package]
name = "tweetsie"
version = "0.1.0"
authors = ["Sammy James"]

[dependencies]
twitter-stream = "0.1"
futures = "0.1.9"


[dependencies.gtk]
git = "https://github.com/gtk-rs/gtk.git"
features = ["v3_16"]